input_type: "image"
dataset_name: "HAM1000"
model:
  encoder: 'resnet18'
  optimizer:
    name: Adam
    lr: 0.0003
    weight_decay: 3e-4
  freeze_base: True

dataset:
  root_path: "HAM1000"
  split_ratios: [0.7, 0.2, 0.1]
  target_size: [224, 224]

num_classes: 2
batch_size: 16
max_epochs: 3
min_epochs: 3
output_dir: outputs
seed: 42